"""
Django settings for ecom_product_comparison project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# MongoEngine connection setup
from mongoengine import connect

from urllib.parse import quote_plus

from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z77abe(yb7i)r$=2_)2)=22^2km#09c66aljgin^dg(jwmx9*g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecom_product_comparison_app',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_mongoengine',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom_product_comparison.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom_product_comparison.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Added Manually

# MongoDB Atlas Configuration
username=quote_plus("QuantumAutomate")
password=quote_plus("Aryan2901@")

connect(
    db="EcomProductComparison",
    username=username,
    password=password,
    host=f"mongodb+srv://{username}:{password}@mongo-practice.r6isy.mongodb.net/",
    authentication_source='admin'
)

# MongoDB Atlas Database configuration for django_mongoengine
MONGODB_DATABASES = {
    'default': {
        'NAME': 'EcomProductComparison',  # Your MongoDB Atlas database name
        'HOST': f"mongodb+srv://{username}:{password}@mongo-practice.r6isy.mongodb.net/",  # Your MongoDB Atlas connection string
        'USERNAME': {username},  # Replace with your MongoDB Atlas username
        'PASSWORD': {password},  # Replace with your MongoDB Atlas password
        'AUTH_SOURCE': 'admin',  # Authentication database (default: 'admin')
        'SSL': True,  # Use SSL (recommended for production)
    }
}



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "ecom_product_comparison_app.authentication.MongoDBJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}



SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),  # Token expires after 1 hour
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),  # Refresh token lasts 7 days
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "email",  # Change this to match your User model field
    "USER_ID_CLAIM": "user_id",
}


# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React frontend URL
# ]

# Allow All Origins for Development
CORS_ALLOW_ALL_ORIGINS = True  # 🔴 (Use only in development)


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'eshopweb2901@gmail.com'
EMAIL_HOST_PASSWORD = 'myuw dsek lyjf kssi'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
